# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageRepository: 'test'
  ContainerRegistry: 'azadpk8szbaqidiwn16d.azurecr.io'


stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push to container registry
      inputs:
        command: 'buildAndPush'
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'